# Generated by Django 4.2.3 on 2023-11-21 09:58

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocieteAviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='societeAviation/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'SocietesAviation',
            },
        ),
        migrations.CreateModel(
            name='TrajetVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trajet_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijk1234567890', length=20, max_length=30, prefix='', unique=True)),
                ('depart', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('prix', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.societeaviation')),
            ],
            options={
                'verbose_name_plural': 'SocietesAviation',
            },
        ),
    ]
