# Generated by Django 4.2.3 on 2023-12-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trajetvoyage',
            options={'verbose_name_plural': 'Trajets voyage'},
        ),
    ]
