# Generated by Django 4.2.3 on 2023-12-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_cartorder_adresse_cartorder_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
